//
// Created by SHA on 10/17/20.
//

#ifndef UCFQUSIM_CONFIG_H
#define UCFQUSIM_CONFIG_H


#define DAG_SCHEME false
#define INIT_MAPPING_RESTRICT_MODE true
#define K 8
#define INIT_MAPPING_DEFAULT_ONLY false
#define TOTAL_PERM 200
#define MAPPING_THRESHOLD 5
#define RANDOM_SAMPLING_INIT_MAPPINGS false
#define INIT_MAPPING_START_NODE_RANK_WISE false
#define RANDOM_SAMPLING_MAPPINGS_PRUNING true

#define RANDOM_SAMPLING_RUNS 40



#endif //UCFQUSIM_CONFIG_H
