//
// Created by hammad on 10/17/20.
//

#ifndef UCFQUSIM_CONFIG_H
#define UCFQUSIM_CONFIG_H


#define DAG_SCHEME false
#define INIT_MAPPING_RESTRICT_MODE true
#define K 8
#define INIT_MAPPING_DEFAULT_ONLY false
#define TOTAL_PERM 2000
#define MAPPING_THRESHOLD 500
#define RANDOM_SAMPLING_INIT_MAPPINGS true
#define INIT_MAPPING_START_NODE_RANK_WISE true
#define RANDOM_SAMPLING_MAPPINGS_PRUNING false

#define RANDOM_SAMPLING_RUNS 40



#endif //UCFQUSIM_CONFIG_H
