//
// Created by SHA on 10/17/20.
//

#ifndef UCFQUSIM_CONFIG_H
#define UCFQUSIM_CONFIG_H


#define DAG_SCHEME false
#define INIT_MAPPING_RESTRICT_MODE false
#define K 8
#define INIT_MAPPING_DEFAULT_ONLY true
#define TOTAL_PERM 100
#define MAPPING_THRESHOLD 10
#define RANDOM_SAMPLING_INIT_MAPPINGS false
#define INIT_MAPPING_START_NODE_RANK_WISE false
#define RANDOM_SAMPLING_MAPPINGS_PRUNING false

#define RANDOM_SAMPLING_RUNS 5



#endif //UCFQUSIM_CONFIG_H
